### ISSUE TITLE
Release support?

### ISSUE THREAD

**Issue by oubiwann** [clojerl/rebar3_clojerl#79]
I saw that there is a template for `clojerl_app` ... does this map to `rebar3 new app ...`? 

I've been making exclusive use of `rebar3 new release ...` to build release-based projects and am very happy with this approach; are there plans to support a template for that in the Clojerl rebar3 plugin?

**Comment by jfacorro** [comment]
I think that is a good idea, we can create a `release` template.  

The `release` command from `rebar3` works out of the box with Clojerl applications, although it requires to run `rebar3 clojerl compile` first. Adding a `clojerl release` command could jut reutilize `rebar3 release` command but require `clojerl compile` as dependency.

**Comment by jfacorro** [comment]
@oubiwann The latest recently cut release 0.8.0 includes a `release` command and a `clojerl_release` template (amongst other things and improvements). 😄 🎉

**Comment by oubiwann** [comment]
WAT

That is _awesome !!!_

**Comment by oubiwann** [comment]
So, I just ran this:
```shell
$ rebar3 new clojerl_release example2
```
```
===> Writing example2/README.md
===> Writing example2/LICENSE
===> Writing example2/rebar.config
===> Writing example2/.gitignore
===> Writing example2/src/example2/core.clje
===> Writing example2/src/example2/app.clje
===> Writing example2/src/example2/sup.clje
===> Writing example2/src/example2.app.src
===> Writing example2/test/example2/core_test.clje
===> Writing example2/config/sys.config
===> Writing example2/config/vm.args
```
But that's different from what I get when I generate a new vanilla Erlang release-based project with `rebar3`:
```shell
$ rebar3 new release example1
```
```
===> Writing example1/apps/example1/src/example1_app.erl
===> Writing example1/apps/example1/src/example1_sup.erl
===> Writing example1/apps/example1/src/example1.app.src
===> Writing example1/rebar.config
===> Writing example1/config/sys.config
===> Writing example1/config/vm.args
===> Writing example1/.gitignore
===> Writing example1/LICENSE
===> Writing example1/README.md
```

Is this intentional or accidental? (if intentional, I'm all ears and want to understand! if accidental, I can submit a PR ;-))

**Comment by oubiwann** [comment]
Another different between the `clojerl_release` and `release` ... the rebar3 Erlang release plugin creates the following `vm.args`:
```erlang
-sname NAME

-setcookie NAME_cookie

+K true
+A30
```

While the clojerl release plugin creates this one:

```erlang
sname NAME

-setcookie NAME_cookie

-mode interactive

+K true
+A30
```

**Comment by jfacorro** [comment]
> Is this intentional or accidental? (if intentional, I'm all ears and want to understand! if accidental, I can submit a PR ;-))

I think it's a little bit of both 😄. 

It is accidental in the sense that I didn't compare the directory structure result from running `rebar3 new release ...`. 

It is intentional in the sense that I haven't really tried an umbrella project with Clojerl. I think it should work since the plugin uses the application discovery from `rebar3` itself, but it's something that needs to be confirmed before replicating the same directory structure.

I can give it a try today and maybe we can just merge #82.

**Comment by jfacorro** [comment]
> That extra mode entry may be what's causing this warning when I run the release?

The `interactive` mode is currently necessary because of a shortcoming in the way Clojerl loads modules. When using `embedded` mode on a release we get the following error:

```
=CRASH REPORT==== 8-Jul-2020::18:58:30.228672 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.432.0>
    registered_name: []
    exception exit: {bad_return,
                     {{clojerl_app,start,[normal,[]]},
                      {'EXIT',
                       {#{'__type__' => 'clojerl.Error',
                          message =>
                           <<"NO_SOURCE_FILE:?:?: Could not locate clojure.core.server.beam or clojure/core/server on code path.">>},
                        [{'clojure.core','load-lib',3,
                          [{file,
                            "/Users/juan.facorro/playground/fooclj/_build/default/lib/clojerl/src/clj/clojure/core.clje"},
                           {line,4588}]},
                         {'clojure.core','-load-libs/1-loop_858/4-0-',5,
                          [{file,
                            "/Users/juan.facorro/playground/fooclj/_build/default/lib/clojerl/src/clj/clojure/core.clje"},
                           {line,4622}]},
                         {clojerl_app,init,0,                                                                                                                                                                      [{file,                                                                                                                                                                                    "/Users/juan.facorro/playground/fooclj/_build/default/lib/clojerl/src/erl/clojerl_app.erl"},                                                                                            {line,42}]},                                                                                                                                                                           {clojerl_app,start,2,                                                                                                                                                                     [{file,
                            "/Users/juan.facorro/playground/fooclj/_build/default/lib/clojerl/src/erl/clojerl_app.erl"},                                                                                            {line,18}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.431.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.433.0>,normal}]
    links: [<0.431.0>,<0.393.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 201
  neighbours:
```

I have to figure out why this is the case. I've been using the `interactive` mode so far as a workaround, but it should be possible to use `embedded` as well.

**Comment by jfacorro** [comment]
I think I've found the root cause.

The problem is that when creating the release the boot script created by relx, which indicates which modules to load when the VM starts doesn't include any of the Clojerl namespaces.

Until there is a fix for this it will be necessary to specific an `interactive` mode for the Clojerl releases. 😞

**Comment by oubiwann** [comment]
Ah, good to know! I had tried debugging that error and didn't make any progress -- thanks!
