### ISSUE TITLE
Issues running a Clojerl release

### ISSUE THREAD

**Issue by oubiwann** [clojerl/rebar3_clojerl#83]
This is a follow up to the discovery work that @jfacorro did here:
* https://github.com/clojerl/rebar3_clojerl/issues/79#issuecomment-655640588
* https://github.com/clojerl/rebar3_clojerl/issues/79#issuecomment-655658138 <-- possible root cause

Basically, when I try to run a Clojerl application using the script resulting from `rebar3 release` (e.g., executing `./_build/default/rel/NAME/bin/NAME console`), I get an error like the following:

```erlang
=INFO REPORT==== 9-Jul-2020::20:45:14.018627 ===
    application: clojerl
    exited: {bad_return,
                {{clojerl_app,start,[normal,[]]},
                 {'EXIT',
                     {#{'__type__' => 'clojerl.Error',
                        message =>
                            <<"NO_SOURCE_FILE:?:?: Could not locate clojure.core.server.beam or clojure/core/server on code path.">>},
                      [{'clojure.core','load-lib',3,
                           [{file,
                                "/Users/oubiwann/lab/clojusc/port-examples/_build/default/lib/clojerl/src/clj/clojure/core.clje"},
                            {line,4588}]},
                       {'clojure.core','-load-libs/1-loop_858/4-0-',5,
                           [{file,
                                "/Users/oubiwann/lab/clojusc/port-examples/_build/default/lib/clojerl/src/clj/clojure/core.clje"},
                            {line,4622}]},
                       {clojerl_app,init,0,
                           [{file,
                                "/Users/oubiwann/lab/clojusc/port-examples/_build/default/lib/clojerl/src/erl/clojerl_app.erl"},
                            {line,42}]},
                       {clojerl_app,start,2,
                           [{file,
                                "/Users/oubiwann/lab/clojusc/port-examples/_build/default/lib/clojerl/src/erl/clojerl_app.erl"},
                            {line,18}]},
                       {application_master,start_it_old,4,
                           [{file,"application_master.erl"},{line,277}]}]}}}}
    type: permanent
```

As a sanity check, I was able to run this application from the Clojerl REPL just fine:
```clj
clje.user=> (application/ensure_all_started :ports)
:ok
clje.user=> (ports.echo/echo "hey, it's a thing")
"hey, it's a thing"
```

The one difference I can note between the issue above and what Juan was seeing (in the comments at the above links) is that  my `vm.args` does have the `-mode interactive` line present. I confirmed that it was actually in `build/default/rel/ports/releases/0.1.0/vm.arg`, too.

**Comment by oubiwann** [comment]
My kerl builds are old, so I'll update those and work back through some recent Erlang versions and see if I witness any different behaviour ...

**Comment by oubiwann** [comment]
On Erlang 22.3 it crashes with this error:
```erlang
=INFO REPORT==== 10-Jul-2020::00:00:41.214853 ===
    application: ports
    exited: {bad_return,
                {{'ports.app',start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{'ports.app',start,[normal,[]],[]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,277}]}]}}}}
    type: permanent
```

I also tried removing the interactive mode from the `vm.args` and updated the release script to use `interactive` instead of `embedded` and that didn't seem to affect anything other than removing the warning log message

**Comment by jfacorro** [comment]
@oubiwann Do you have a public repository that would allow to reproduce the behaviour?

**Comment by oubiwann** [comment]
Just pushed the code here:
* https://github.com/clojusc/clojerl-port-examples

Since I can't test using the release script, I've been starting up the REPL (using `make repl` which gives me command history with `rlwrap`) and executing the following:

```clj
(application/ensure_all_started :ports)
(ports.echo/echo "hey, it's a thing")
```

Note that I currently have the log level set to debug, so you'll see more sent to stdout than you might be used to ;-)

**Comment by oubiwann** [comment]
So, I think that second error I pasted in the comment is actually a red herring: it seems that `rebar3 compile` doesn't trigger `rebar3 clojerl compile`; when I do the latter, that error no longer results (as one would expect, upon examining that error in more detail).

With that realization, I've re-tested with Erlang 23.0 and 22.3 and get the same error (the one pasted in the ticket description; I couldn't get clojerl to run with my current rebar3 install on Erlang 20.3 or 21.3.

Also: I pushed a couple of tweaks to that repo (there was a minor regression in the sys config file).

**Comment by oubiwann** [comment]
Oh wait!! 

I didn't add the ENV var `CODE_LOADING_MODE` to `make run` in the `Makefile`! That works!!!

(I was testing by manually editing files, which didn't work ... but I probably missed something.)

```erlang
(ports@spacemac)1> 'ports.echo':echo("hey, it's a thing").
"hey, it's a thing"
```

I'm running with the release `console` option, which of course puts me into the Erlang Shell. I wonder what the best way to run the Clojerl REPL from a release would be ...?

**Comment by oubiwann** [comment]
In LFE, it's possible to switch from the Erlang shell to the LFE REPL by simply starting up the REPL. Is that something that Clojerl supports?

Ah, yes!
```erlang
> 'clojure.main':main([<<"-r">>]).
```
```clj
Clojure 0.6.0
clje.user=> 
```

Looks like I can run a REPL directly if instead of doing this:
```shell
CODE_LOADING_MODE=interactive $(PROJ_BIN) console
```
I do this:
```shell
CODE_LOADING_MODE=interactive $(PROJ_BIN) start
$(PROJ_BIN) eval "'clojure.main':main([<<\"-r\">>])"
$(PROJ_BIN) attach;
```

**Comment by oubiwann** [comment]
Hrm, maybe more than just the call to `main` is needed, though. 

If I make my test echo call:
```clj
clje.user=> (ports.echo/echo "hey, it's a thing")
```
I get this:
```clj
clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=> clje.user=>
```

If I switch to starting up a release console, and then start the Clojure REPL manually via an Erlang call, I see more of what's going on, getting this after making the `echo` call:
```clj
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> ports.echo/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> orts.echo/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> rts.echo/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> ts.echo/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> s.echo/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> .echo/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> echo/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> cho/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> ho/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> o/echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> /echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> echo "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> cho "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> ho "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> o "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=>  "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> "hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> hey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> ey, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> y, it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> , it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=>  it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> it's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
clje.user=> t's a thing")
Couldn't unread to erlang.io.PushbackReader: :badargclje.user=> 
's a thing")
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg
Couldn't unread to erlang.io.PushbackReader: :badarg

clje.user=>  a thing")
clje.user=> a thing")
clje.user=>  thing")
clje.user=> thing")
clje.user=> hing")
clje.user=> ing")
clje.user=> ng")
clje.user=> g")
clje.user=> ")
clje.user=> )
clje.user=> 
clje.user=> 
```

**Comment by jfacorro** [comment]
@oubiwann I merged #84 and built a release in the project you shared. The release is successfully starting now. 

I'm attaching a screenshot with the minor changes I did to the `Makefile` and `rebar.config`.
<img width="1792" alt="Screenshot 2020-07-10 at 18 20 20" src="https://user-images.githubusercontent.com/1522569/87176520-83e98600-c2da-11ea-99b7-beed4c4d05f4.png">

**Comment by jfacorro** [comment]
> In LFE, it's possible to switch from the Erlang shell to the LFE REPL by simply starting up the REPL. Is that something that Clojerl supports?
> 
> Ah, yes!
> 
> ```erlang
> > 'clojure.main':main([<<"-r">>]).
> ```
> 
> ```clojure
> Clojure 0.6.0
> clje.user=> 
> ```
> 
> Looks like I can run a REPL directly if instead of doing this:
> 
> ```shell
> CODE_LOADING_MODE=interactive $(PROJ_BIN) console
> ```
> 
> I do this:
> 
> ```shell
> CODE_LOADING_MODE=interactive $(PROJ_BIN) start
> $(PROJ_BIN) eval "'clojure.main':main([<<\"-r\">>])"
> $(PROJ_BIN) attach;
> ```

That is a good point and a good thing to have. I would rather address this in a different issue though 😄. 

Would it be possible for you to open a different issue for this? 🙏

**Comment by oubiwann** [comment]
@jfacorro Absolutely!

Sorry, got into stream-of-consciousness mode ;-)

**Comment by oubiwann** [comment]
I created two tickets for the above comments, and now will test the latest updates to the plugin (I might already have them, though -- I've been running the rebar3 clojerl plugin off of master for the past day ...)

**Comment by oubiwann** [comment]
Hrm, looks like I'm running into a new problem with the latest plugin code in master:

If I don't compile the Clojerl code before I run a release, I get the same error I mentioned above (`{'ports.app',start,[normal,[]]}` undefined, etc.).

If I _do_ compile first (which worked above), I now get an error:
```
===> Verifying dependencies...
===> Compiling clojerl
===> Compiling ports
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /Users/oubiwann/lab/clojusc/port-examples/_build/default/lib
          /Users/oubiwann/lab/clojusc/port-examples/apps
          /opt/erlang/23.0/lib
===> Resolved ports-0.1.0
===> Dev mode enabled, release will be symlinked
===> Errors generating release 
          Duplicated modules: 
        'erlang.io.IWriter' specified in clojerl and ports
        'erlang.io.IReader' specified in clojerl and ports
        'erlang.io.IPushbackReader' specified in clojerl and ports
        'erlang.io.ICloseable' specified in clojerl and ports
        'clojerl.IType' specified in clojerl and ports
        'clojerl.IStringable' specified in clojerl and ports
        'clojerl.ISequential' specified in clojerl and ports
        'clojerl.ISeqable' specified in clojerl and ports
        'clojerl.IReduce' specified in clojerl and ports
        'clojerl.IRecord' specified in clojerl and ports
        'clojerl.IMeta' specified in clojerl and ports
        'clojerl.IMap' specified in clojerl and ports
        'clojerl.ILookup' specified in clojerl and ports
        'clojerl.IHash' specified in clojerl and ports
        'clojerl.IEquiv' specified in clojerl and ports
        'clojerl.IDeref' specified in clojerl and ports
        'clojerl.ICounted' specified in clojerl and ports
        'clojerl.IColl' specified in clojerl and ports
        'clojerl.IAssociative' specified in clojerl and ports
```

But maybe I haven't updated my workflow to what it should be? Here's a sample set of tasks I do for a completely clean build:

1. `rebar3 clean`
1. `rm -rf _build`
1. `rebar3 clojerl compile`
1. `rebar3 release` <-- this is where it fails
1. `CODE_LOADING_MODE=interactive $(PROJ_BIN) console`

**Comment by oubiwann** [comment]
Ah! It works if I remove `clojerl` from my `.app.src` file :-) 

I think we're good to close this issue!

**Comment by oubiwann** [comment]
Thanks SO MUCH for all your help, Juan! ❤️

**Comment by jfacorro** [comment]
No problem! I'm very happy to help if it means Clojerl is getting used 😄.
